do
  local vim = vim
  local Plug = vim.fn["plug#"]
  vim.call("plug#begin")
  Plug("junegunn/seoul256.vim")
  Plug("SirVer/ultisnips")
  Plug("airblade/vim-gitgutter")
  Plug("godlygeek/tabular")
  Plug("junegunn/rainbow_parentheses.vim")
  Plug("junegunn/vim-peekaboo")
  Plug("justinmk/vim-gtfo")
  Plug("MTDL9/vim-log-highlighting")
  Plug("mbbill/undotree")
  Plug("scrooloose/nerdcommenter")
  Plug("thirtythreeforty/lessspace.vim")
  Plug("vim-scripts/a.vim")
  Plug("vim-scripts/taglist.vim")
  Plug("w0rp/ale")
  Plug("tmhedberg/matchit")
  Plug("andymass/vim-matchup")
  Plug("vim-airline/vim-airline")
  Plug("vim-airline/vim-airline-themes")
  Plug("vim-scripts/ConflictMotions")
  Plug("vim-scripts/CountJump")
  Plug("vim-scripts/ingo-library")
  local function _1_()
    return vim.fn["fzf#install"]()
  end
  Plug("junegunn/fzf", {["do"] = _1_})
  Plug("junegunn/fzf.vim")
  Plug("pbogut/fzf-mru.vim")
  Plug("tpope/vim-eunuch")
  Plug("tpope/vim-fugitive")
  Plug("tpope/vim-repeat")
  Plug("tpope/vim-surround")
  Plug("tpope/vim-vinegar")
  Plug("tpope/vim-abolish")
  Plug("vhda/verilog_systemverilog.vim")
  Plug("vim-scripts/VIP")
  Plug("lervag/vimtex")
  Plug("JuliaEditorSupport/julia-vim")
  Plug("gabrielelana/vim-markdown")
  Plug("jceb/vim-orgmode")
  Plug("NLKNguyen/papercolor-theme")
  Plug("chriskempson/base16-vim")
  Plug("dmcgrady/vim-lucario")
  Plug("dracula/vim")
  Plug("guns/jellyx.vim")
  Plug("zeis/vim-kolor")
  Plug("lifepillar/vim-solarized8")
  Plug("morhetz/gruvbox")
  Plug("patstockwell/vim-monokai-tasty")
  Plug("iCyMind/NeoSolarized")
  Plug("liuchengxu/vim-which-key")
  vim.call("plug#end")
end
do
  vim.api.nvim_set_keymap("n", "<leader>", ":WhichKey '<Space>'<CR>", {noremap = true, silent = true})
end
return true
