#!/bin/bash
# re-align an org mode table

if [ $# -lt 1 ];then
  echo "Usage: $(basename "$0") FILES"
  exit 1
fi

if ! command -v emacs &> /dev/null
then
    echo "Emacs not in path :("
    exit
fi

DIR=$(pwd)
FILES=""
# wrap each argument in the code required to call tangle on it
for i in "$@"; do
    FILES="$FILES \"$i\""
done

emacs -Q --batch \
    --eval "(progn
     (require 'org)
     (require 'org-table)
     (mapc (lambda (file)
            (find-file (expand-file-name file \"$DIR\"))
            (org-table-map-tables 'org-table-align)
            (write-file file nil)
            (kill-buffer)) '($FILES)))"
