#!/usr/bin/env bash
for dir in "$(pwd)"/*/ # list directories in the form "/tmp/dirname/"
do
    dir=${dir%*/}      # remove the trailing "/"
    cd "$dir" || exit
    cnt=$(find . -type f | wc -l)
    echo "$cnt" $'\t' ${dir##*/} # print everything after the final slash
    cd ..
done | sort -n
