#!/usr/bin/env bash
#echo "file://$1" | setsid xclip -i -selection clipboard -t text/uri-list &
{
    for i in "$@"; do
        echo -en "file://$(realpath "${i}")\n"
    done
} | setsid xclip -i -sel c -rmlastnl -t text/uri-list
