#!/usr/bin/env sh

if [ $# -ne 1 ];then
  echo "Usage: $(basename "$0") FILE"
  exit 1
fi

emacs -batch -Q "$1" --eval '(progn (setq tab-width 2) (setq indent-tabs-mode nil) (indent-region (point-min) (point-max) nil) (save-buffer))'
