#!/usr/bin/env bash

if [ $# -ne 1 ];then
  echo "Usage: $(basename "$0") ARCHIVE"
  exit 1
fi

if [ -f "$1" ] ; then
  case $1 in
    *.tar.gz)   tar xzf    "$1" ;;
    *.tar.bz2)  tar xjf    "$1" ;;
    *.tar.zst)  tar xaf    "$1" ;;
    *.7z)       7zip x     "$1" ;;
    *.gz)       gzip       "$1" ;;
    *.rar)      unrar x    "$1" ;;
    *.tar)      tar xf     "$1" ;;
    *.bz2)      bunzip2    "$1" ;;
    *.tbz2)     tar xjf    "$1" ;;
    *.tgz)      tar xzf    "$1" ;;
    *.xz)       tar xvf    "$1" ;;
    *.Z)        uncompress "$1" ;;
    *.zip)      unzip      "$1" ;;
    *)          echo       "'$1' cannot be extracted via extract()" ;;
  esac
else
  echo "'$1' is not a valid file"
fi
