#!/usr/bin/env bash

if [ -z "$2" ]
  then
    echo "this should be run as run-with-date 2023-01-22 program_name"
    exit 1
fi

#2020-03-15
CMD1="faketime\ -f\ \"@$1\ 15:02:06\"\ $2"
CMD="bash -c $CMD1"

echo "$CMD1"

echo configuring iptables
sudo iptables -F
sudo iptables -I OUTPUT 1 -m owner --gid-owner no-internet -j DROP

echo starting...
sg no-internet "$CMD"
